import { V } from 'framer-motion/dist/types.d-DDSxwf0n';
import { CATEGORIES } from './constants';

export const ApiRoutes = {
  ALL_CATEGORES: 'categories',
  RESET_PASSWORD: 'users/resetPassword',
  FORGOT_PASSWORD: 'users/forgotPassword',
  VIRTUAL_TOWN_HALL: '/virtualTownhall',
  GET_TOURISM_SERVICE: '/tourismLeisure',
  GET_RECOMMEND: '/listings/recommend',
  GET_MOBILITY_SERVICE: '/mobility',
  GET_CITY_BY_ID: (id: string) => `/cities/${id}`,
  GET_CATEGORY_BY_ID: (id: string) => `/listings?categoryId=${id}`,
  FAVORITES_CITIES: (userId: string) => `/users/favorites/cities`,
  Mein_Ort: '/meinOrt',
  GET_CITIES_BY_ID: (id: string) => `/cities?parentId=${id}`,
  MuNICIPAL_BY_ID: (id: string) => `/virtualTownhall/getMunicipalityById?municipalityId=${id}`,
  MITCHMEN: '/participate',
  LISTINGS: 'listings',
  SUB_CATEGORIES_BY_ID: (id: string) => `categories/${id}/subcategories`,
  USERS: 'users/me',
  LOGIN: 'users/login',
  SEARCH_LISTING: 'listings/search',
  REGISTER: 'users/register',
  MARK_EVENT_FAVORITE: (userId: string) => `users/favorites`,
  MARK_CITY_FAVORITE: (userId: string) => `users/favorites/cities`,
  DELETE_EVENT_FAVORITE: (userId: string, favoriteId: string) => `users/favorites/${favoriteId}`,
  DELETE_CITY_FAVORITE: (userId: string, cityId: string) => `users/favorites/cities/${cityId}`,
  USER_DELETE: (userId: string) => `users/`,
  EVENT_BY_ID: (eventId: string | number) => `/listings/${eventId}`,
  REFRESH_TOKEN_BY_USER_ID: (userId: string) => `users/refresh`,
  GET_USER_FAVORITES: (userId: string) => `users/favorites/listings`,
  SET_USER_TYPE: (userId: string) => `users/userType`,
  SET_USER_DEMOGRAPHICS: (userId: string) => `users/demographics`,
  SET_USER_INTEREST: (userId: string) => `users/interests`,
  SET_USER_ONBOARDING_COMPLETE: (userId: string) => `/users/onboardingComplete`,
  GET_CITIES: '/cities',
  GET_CITIES_FOR_CITY_ADMIN: '/cities/admin-cities',
  FEEDBACKS: '/feedbacks',
  VERIFY_EMAIL: '/users/verifyEmail',
  GET_USER_ONBOARDING_DETAIL: (userId: string | number) => `users/onboardingDetail`,
  INTERESTS: '/interests',
  USERS_LIST: '/users',
  CITY_ADMIN: (cityId: number) => `/cities/${cityId}/admin`,
  INVITE_USER: '/users/invite',
  GET_INVITED_USERS: '/users/invited',
};

export const APPROUTES = {
  LOGIN: '/login',
  PASSWORD_FORGOT: '/PasswordForgot',
  REGISTER: '/signup',
  EVENTS: '/events',
  EVENT_BY_ID: '/events/$id',
  NEWS: '/news',
  NAVIGATE_EVENTS_BY_ID: (id: string | number) => `/events/${id}`,
  NAVIGATE_NEWS_BY_ID: (id: string | number) => `/news/${id}`,
  DISCOVER: '/discover',
  DISCOVER_BY_ID: '/discover/$id',
  NAVIGATE_DISCOVER_BY_ID: (id: string | number) => `/discover/${id}`,
  DISCOVER_EVENTS_IN_SUBCATEGORY: '/discover/$categoryId/$subCategoryId',
  HOME: '/',
  USER_SETTINGS: '/users/settings',
  FEEDBACK: '/feedback',
  ONBOARDING: '/onboarding',
  FAVORITES: '/favorites',
  FAVORITE_CITIES: `/favoritecities`,
  MAPS: '/maps',
  IMPRESSUM: '/impressum',
  TERMS: '/terms',
  PRIVACY_POLICY: '/privacy-policy',
  VERIFY_EMAIL: '/VerifyEmail',
  DASHBOARD: '/dashboard',
  UPLOAD_LISTING: '/dashboard/upload',
  MY_LISTINGS: '/dashboard/my-listings',
  ALL_LISTINGS: '/dashboard/all-listings',
  VIEW_LISTING: '/dashboard/listing/$listingId',
  CITIES: '/cities',
};

export const queryKeys = {
  ALL_CATEGORIES: 'all-category-detail',
  ALL_CATEGORIES_MAP: 'all-catgeory-map',
  FORGOT_PASSWORD: 'forgot-password',
  CHANGE_PASSWORD: 'change-password',
  GET_LISTINGS: 'get-listings',
  GET_SUB_CATEGORIES: 'get-subCategories',
  USER_DETAILS: 'userDetails',
  LOGIN: 'login',
  SEARCH_LISTING: 'search-listing',
  SIGNUP: 'signup',
  MARK_EVENT_FAVORITE: 'mark-event-favorite',
  DELETE_EVENT_FAVORITE: 'delete-event-favorite',
  DELETE_USER_ACCOUNT: 'delete-user-account',
  EVENT_BY_ID: 'event-by-id',
  GET_ALL_Favorites: 'user-all-favorites',
  GET_INTEREST: 'get-interest',
  GET_CITIES: 'get-cities',
  GET_ADMIN_CITIES: 'get-admin-cities',
  GET_EVENTS_IN_SUBCATEGORY: 'get-events-in-subcategory',
  GET_VTH: 'get-virtual-town-hall',
  GET_MUNICIPAL_BY_ID: 'get-municipal-by-id',
  GET_CITIES_BY_ID: 'get-cities-by-id',
  Get_Mein_Ort: 'get-mein-ort',
  GET_CITY_BY_ID: 'get-city-by-id',
  GET_Tourism: 'get-tourism',
  GET_Mobility: 'get-mobility',
  GET_MITCHMEN: 'get-mitchmen',
  GET_CATEGORY_BY_ID: 'get-category-by-id',
  MARK_CITY_FAVORITE: 'mark-city-favorite',
  DELETE_CITY_FAVORITE: 'delete-city-favorite',
  VERIFY_EMAIL: 'verify-users-email',
  GET_FAV_CITIES: 'get-favorite-cities',
  GET_CITY_ADMINS: 'GET_CITY_ADMINS',
  GET_USERS: 'GET_USERS',
  INVITED_USERS: 'INVITED_USERS',
  // User related
  PROFILE: (userId?: string, params?: any) => ['profile', userId, params],
  USER_FAVORITES: (userId: string) => ['userFavorites', userId],
  USER_TYPE: (userId: string) => ['userType', userId],
  USER_DEMOGRAPHICS: (userId: string) => ['userDemographics', userId],
  USER_INTERESTS: (userId: string) => ['userInterests', userId],

  // Listings
  LISTINGS: (params?: any) => ['listings', params],
  MY_LISTINGS: (params?: any) => ['myListings', params],
  LISTING_DETAIL: (id: string) => ['listing', id],
  SEARCH_LISTINGS: (params?: any) => ['searchListings', params],

  // Categories
  CATEGORIES: ['categories'],
  CATEGORY_DETAIL: (id: string) => ['category', id],

  // Cities
  CITIES: ['cities'],
  CITY_DETAIL: (id: string) => ['city', id],

  // Services
  // TOURISM_SERVICES: ['tourismServices'],
  // MOBILITY_SERVICES: ['mobilityServices'],
  // VIRTUAL_TOWN_HALL: ['virtualTownHall'],

  // // Auth
  // FORGOT_PASSWORD: ['forgotPassword'],
  // RESET_PASSWORD: ['resetPassword'],
  // VERIFY_EMAIL: ['verifyEmail'],

  // // Feedback
  // FEEDBACKS: ['feedbacks'],
  SUBCATEGORIES: ['subcategories'],
};
