/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FavoritecitiesRouteImport } from './routes/favoritecities'
import { Route as EditonboardingRouteImport } from './routes/editonboarding'
import { Route as VerifyEmailRouteImport } from './routes/VerifyEmail'
import { Route as PasswordForgotRouteImport } from './routes/PasswordForgot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VirtualtownhallIndexRouteImport } from './routes/virtualtownhall/index'
import { Route as TourismIndexRouteImport } from './routes/tourism/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NearyouIndexRouteImport } from './routes/nearyou/index'
import { Route as MobilityIndexRouteImport } from './routes/mobility/index'
import { Route as MitchmachenIndexRouteImport } from './routes/mitchmachen/index'
import { Route as MeinortIndexRouteImport } from './routes/meinort/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CitiesIndexRouteImport } from './routes/cities/index'
import { Route as VirtualtownhallIdRouteImport } from './routes/virtualtownhall/$id'
import { Route as UsersSettingsRouteImport } from './routes/users/settings'
import { Route as NewsIdRouteImport } from './routes/news/$id'
import { Route as MeinortIdRouteImport } from './routes/meinort/$id'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as DiscoverIdRouteImport } from './routes/discover/$id'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as DashboardEditlistingRouteImport } from './routes/dashboard/editlisting'
import { Route as DashboardAllListingsRouteImport } from './routes/dashboard/all-listings'
import { Route as VirtualtownhallViewAllcitiesIdRouteImport } from './routes/virtualtownhall/viewAllcities/$id'
import { Route as DiscoverCategoryIdSubCategoryIdRouteImport } from './routes/discover/$categoryId/$subCategoryId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritecitiesRoute = FavoritecitiesRouteImport.update({
  id: '/favoritecities',
  path: '/favoritecities',
  getParentRoute: () => rootRouteImport,
} as any)
const EditonboardingRoute = EditonboardingRouteImport.update({
  id: '/editonboarding',
  path: '/editonboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/VerifyEmail',
  path: '/VerifyEmail',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/PasswordForgot',
  path: '/PasswordForgot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualtownhallIndexRoute = VirtualtownhallIndexRouteImport.update({
  id: '/virtualtownhall/',
  path: '/virtualtownhall/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismIndexRoute = TourismIndexRouteImport.update({
  id: '/tourism/',
  path: '/tourism/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NearyouIndexRoute = NearyouIndexRouteImport.update({
  id: '/nearyou/',
  path: '/nearyou/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilityIndexRoute = MobilityIndexRouteImport.update({
  id: '/mobility/',
  path: '/mobility/',
  getParentRoute: () => rootRouteImport,
} as any)
const MitchmachenIndexRoute = MitchmachenIndexRouteImport.update({
  id: '/mitchmachen/',
  path: '/mitchmachen/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeinortIndexRoute = MeinortIndexRouteImport.update({
  id: '/meinort/',
  path: '/meinort/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualtownhallIdRoute = VirtualtownhallIdRouteImport.update({
  id: '/virtualtownhall/$id',
  path: '/virtualtownhall/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersSettingsRoute = UsersSettingsRouteImport.update({
  id: '/users/settings',
  path: '/users/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeinortIdRoute = MeinortIdRouteImport.update({
  id: '/meinort/$id',
  path: '/meinort/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIdRoute = DiscoverIdRouteImport.update({
  id: '/discover/$id',
  path: '/discover/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/dashboard/upload',
  path: '/dashboard/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditlistingRoute = DashboardEditlistingRouteImport.update({
  id: '/dashboard/editlisting',
  path: '/dashboard/editlisting',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAllListingsRoute = DashboardAllListingsRouteImport.update({
  id: '/dashboard/all-listings',
  path: '/dashboard/all-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualtownhallViewAllcitiesIdRoute =
  VirtualtownhallViewAllcitiesIdRouteImport.update({
    id: '/virtualtownhall/viewAllcities/$id',
    path: '/virtualtownhall/viewAllcities/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscoverCategoryIdSubCategoryIdRoute =
  DiscoverCategoryIdSubCategoryIdRouteImport.update({
    id: '/discover/$categoryId/$subCategoryId',
    path: '/discover/$categoryId/$subCategoryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/PasswordForgot': typeof PasswordForgotRoute
  '/VerifyEmail': typeof VerifyEmailRoute
  '/editonboarding': typeof EditonboardingRoute
  '/favoritecities': typeof FavoritecitiesRoute
  '/favorites': typeof FavoritesRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/all-listings': typeof DashboardAllListingsRoute
  '/dashboard/editlisting': typeof DashboardEditlistingRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/discover/$id': typeof DiscoverIdRoute
  '/events/$id': typeof EventsIdRoute
  '/meinort/$id': typeof MeinortIdRoute
  '/news/$id': typeof NewsIdRoute
  '/users/settings': typeof UsersSettingsRoute
  '/virtualtownhall/$id': typeof VirtualtownhallIdRoute
  '/cities': typeof CitiesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/events': typeof EventsIndexRoute
  '/meinort': typeof MeinortIndexRoute
  '/mitchmachen': typeof MitchmachenIndexRoute
  '/mobility': typeof MobilityIndexRoute
  '/nearyou': typeof NearyouIndexRoute
  '/news': typeof NewsIndexRoute
  '/tourism': typeof TourismIndexRoute
  '/virtualtownhall': typeof VirtualtownhallIndexRoute
  '/discover/$categoryId/$subCategoryId': typeof DiscoverCategoryIdSubCategoryIdRoute
  '/virtualtownhall/viewAllcities/$id': typeof VirtualtownhallViewAllcitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/PasswordForgot': typeof PasswordForgotRoute
  '/VerifyEmail': typeof VerifyEmailRoute
  '/editonboarding': typeof EditonboardingRoute
  '/favoritecities': typeof FavoritecitiesRoute
  '/favorites': typeof FavoritesRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/all-listings': typeof DashboardAllListingsRoute
  '/dashboard/editlisting': typeof DashboardEditlistingRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/discover/$id': typeof DiscoverIdRoute
  '/events/$id': typeof EventsIdRoute
  '/meinort/$id': typeof MeinortIdRoute
  '/news/$id': typeof NewsIdRoute
  '/users/settings': typeof UsersSettingsRoute
  '/virtualtownhall/$id': typeof VirtualtownhallIdRoute
  '/cities': typeof CitiesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/events': typeof EventsIndexRoute
  '/meinort': typeof MeinortIndexRoute
  '/mitchmachen': typeof MitchmachenIndexRoute
  '/mobility': typeof MobilityIndexRoute
  '/nearyou': typeof NearyouIndexRoute
  '/news': typeof NewsIndexRoute
  '/tourism': typeof TourismIndexRoute
  '/virtualtownhall': typeof VirtualtownhallIndexRoute
  '/discover/$categoryId/$subCategoryId': typeof DiscoverCategoryIdSubCategoryIdRoute
  '/virtualtownhall/viewAllcities/$id': typeof VirtualtownhallViewAllcitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/PasswordForgot': typeof PasswordForgotRoute
  '/VerifyEmail': typeof VerifyEmailRoute
  '/editonboarding': typeof EditonboardingRoute
  '/favoritecities': typeof FavoritecitiesRoute
  '/favorites': typeof FavoritesRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/all-listings': typeof DashboardAllListingsRoute
  '/dashboard/editlisting': typeof DashboardEditlistingRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/discover/$id': typeof DiscoverIdRoute
  '/events/$id': typeof EventsIdRoute
  '/meinort/$id': typeof MeinortIdRoute
  '/news/$id': typeof NewsIdRoute
  '/users/settings': typeof UsersSettingsRoute
  '/virtualtownhall/$id': typeof VirtualtownhallIdRoute
  '/cities/': typeof CitiesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/events/': typeof EventsIndexRoute
  '/meinort/': typeof MeinortIndexRoute
  '/mitchmachen/': typeof MitchmachenIndexRoute
  '/mobility/': typeof MobilityIndexRoute
  '/nearyou/': typeof NearyouIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tourism/': typeof TourismIndexRoute
  '/virtualtownhall/': typeof VirtualtownhallIndexRoute
  '/discover/$categoryId/$subCategoryId': typeof DiscoverCategoryIdSubCategoryIdRoute
  '/virtualtownhall/viewAllcities/$id': typeof VirtualtownhallViewAllcitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/PasswordForgot'
    | '/VerifyEmail'
    | '/editonboarding'
    | '/favoritecities'
    | '/favorites'
    | '/feedback'
    | '/forgot-password'
    | '/impressum'
    | '/login'
    | '/maps'
    | '/onboarding'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/dashboard/all-listings'
    | '/dashboard/editlisting'
    | '/dashboard/upload'
    | '/discover/$id'
    | '/events/$id'
    | '/meinort/$id'
    | '/news/$id'
    | '/users/settings'
    | '/virtualtownhall/$id'
    | '/cities'
    | '/dashboard'
    | '/discover'
    | '/events'
    | '/meinort'
    | '/mitchmachen'
    | '/mobility'
    | '/nearyou'
    | '/news'
    | '/tourism'
    | '/virtualtownhall'
    | '/discover/$categoryId/$subCategoryId'
    | '/virtualtownhall/viewAllcities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/PasswordForgot'
    | '/VerifyEmail'
    | '/editonboarding'
    | '/favoritecities'
    | '/favorites'
    | '/feedback'
    | '/forgot-password'
    | '/impressum'
    | '/login'
    | '/maps'
    | '/onboarding'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/dashboard/all-listings'
    | '/dashboard/editlisting'
    | '/dashboard/upload'
    | '/discover/$id'
    | '/events/$id'
    | '/meinort/$id'
    | '/news/$id'
    | '/users/settings'
    | '/virtualtownhall/$id'
    | '/cities'
    | '/dashboard'
    | '/discover'
    | '/events'
    | '/meinort'
    | '/mitchmachen'
    | '/mobility'
    | '/nearyou'
    | '/news'
    | '/tourism'
    | '/virtualtownhall'
    | '/discover/$categoryId/$subCategoryId'
    | '/virtualtownhall/viewAllcities/$id'
  id:
    | '__root__'
    | '/'
    | '/PasswordForgot'
    | '/VerifyEmail'
    | '/editonboarding'
    | '/favoritecities'
    | '/favorites'
    | '/feedback'
    | '/forgot-password'
    | '/impressum'
    | '/login'
    | '/maps'
    | '/onboarding'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/dashboard/all-listings'
    | '/dashboard/editlisting'
    | '/dashboard/upload'
    | '/discover/$id'
    | '/events/$id'
    | '/meinort/$id'
    | '/news/$id'
    | '/users/settings'
    | '/virtualtownhall/$id'
    | '/cities/'
    | '/dashboard/'
    | '/discover/'
    | '/events/'
    | '/meinort/'
    | '/mitchmachen/'
    | '/mobility/'
    | '/nearyou/'
    | '/news/'
    | '/tourism/'
    | '/virtualtownhall/'
    | '/discover/$categoryId/$subCategoryId'
    | '/virtualtownhall/viewAllcities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EditonboardingRoute: typeof EditonboardingRoute
  FavoritecitiesRoute: typeof FavoritecitiesRoute
  FavoritesRoute: typeof FavoritesRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  DashboardAllListingsRoute: typeof DashboardAllListingsRoute
  DashboardEditlistingRoute: typeof DashboardEditlistingRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DiscoverIdRoute: typeof DiscoverIdRoute
  EventsIdRoute: typeof EventsIdRoute
  MeinortIdRoute: typeof MeinortIdRoute
  NewsIdRoute: typeof NewsIdRoute
  UsersSettingsRoute: typeof UsersSettingsRoute
  VirtualtownhallIdRoute: typeof VirtualtownhallIdRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MeinortIndexRoute: typeof MeinortIndexRoute
  MitchmachenIndexRoute: typeof MitchmachenIndexRoute
  MobilityIndexRoute: typeof MobilityIndexRoute
  NearyouIndexRoute: typeof NearyouIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  TourismIndexRoute: typeof TourismIndexRoute
  VirtualtownhallIndexRoute: typeof VirtualtownhallIndexRoute
  DiscoverCategoryIdSubCategoryIdRoute: typeof DiscoverCategoryIdSubCategoryIdRoute
  VirtualtownhallViewAllcitiesIdRoute: typeof VirtualtownhallViewAllcitiesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritecities': {
      id: '/favoritecities'
      path: '/favoritecities'
      fullPath: '/favoritecities'
      preLoaderRoute: typeof FavoritecitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editonboarding': {
      id: '/editonboarding'
      path: '/editonboarding'
      fullPath: '/editonboarding'
      preLoaderRoute: typeof EditonboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/VerifyEmail': {
      id: '/VerifyEmail'
      path: '/VerifyEmail'
      fullPath: '/VerifyEmail'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PasswordForgot': {
      id: '/PasswordForgot'
      path: '/PasswordForgot'
      fullPath: '/PasswordForgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtualtownhall/': {
      id: '/virtualtownhall/'
      path: '/virtualtownhall'
      fullPath: '/virtualtownhall'
      preLoaderRoute: typeof VirtualtownhallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism/': {
      id: '/tourism/'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearyou/': {
      id: '/nearyou/'
      path: '/nearyou'
      fullPath: '/nearyou'
      preLoaderRoute: typeof NearyouIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobility/': {
      id: '/mobility/'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof MobilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitchmachen/': {
      id: '/mitchmachen/'
      path: '/mitchmachen'
      fullPath: '/mitchmachen'
      preLoaderRoute: typeof MitchmachenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meinort/': {
      id: '/meinort/'
      path: '/meinort'
      fullPath: '/meinort'
      preLoaderRoute: typeof MeinortIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtualtownhall/$id': {
      id: '/virtualtownhall/$id'
      path: '/virtualtownhall/$id'
      fullPath: '/virtualtownhall/$id'
      preLoaderRoute: typeof VirtualtownhallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/settings': {
      id: '/users/settings'
      path: '/users/settings'
      fullPath: '/users/settings'
      preLoaderRoute: typeof UsersSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meinort/$id': {
      id: '/meinort/$id'
      path: '/meinort/$id'
      fullPath: '/meinort/$id'
      preLoaderRoute: typeof MeinortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$id': {
      id: '/discover/$id'
      path: '/discover/$id'
      fullPath: '/discover/$id'
      preLoaderRoute: typeof DiscoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/dashboard/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/editlisting': {
      id: '/dashboard/editlisting'
      path: '/dashboard/editlisting'
      fullPath: '/dashboard/editlisting'
      preLoaderRoute: typeof DashboardEditlistingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/all-listings': {
      id: '/dashboard/all-listings'
      path: '/dashboard/all-listings'
      fullPath: '/dashboard/all-listings'
      preLoaderRoute: typeof DashboardAllListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtualtownhall/viewAllcities/$id': {
      id: '/virtualtownhall/viewAllcities/$id'
      path: '/virtualtownhall/viewAllcities/$id'
      fullPath: '/virtualtownhall/viewAllcities/$id'
      preLoaderRoute: typeof VirtualtownhallViewAllcitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$categoryId/$subCategoryId': {
      id: '/discover/$categoryId/$subCategoryId'
      path: '/discover/$categoryId/$subCategoryId'
      fullPath: '/discover/$categoryId/$subCategoryId'
      preLoaderRoute: typeof DiscoverCategoryIdSubCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EditonboardingRoute: EditonboardingRoute,
  FavoritecitiesRoute: FavoritecitiesRoute,
  FavoritesRoute: FavoritesRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  DashboardAllListingsRoute: DashboardAllListingsRoute,
  DashboardEditlistingRoute: DashboardEditlistingRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DiscoverIdRoute: DiscoverIdRoute,
  EventsIdRoute: EventsIdRoute,
  MeinortIdRoute: MeinortIdRoute,
  NewsIdRoute: NewsIdRoute,
  UsersSettingsRoute: UsersSettingsRoute,
  VirtualtownhallIdRoute: VirtualtownhallIdRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MeinortIndexRoute: MeinortIndexRoute,
  MitchmachenIndexRoute: MitchmachenIndexRoute,
  MobilityIndexRoute: MobilityIndexRoute,
  NearyouIndexRoute: NearyouIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  TourismIndexRoute: TourismIndexRoute,
  VirtualtownhallIndexRoute: VirtualtownhallIndexRoute,
  DiscoverCategoryIdSubCategoryIdRoute: DiscoverCategoryIdSubCategoryIdRoute,
  VirtualtownhallViewAllcitiesIdRoute: VirtualtownhallViewAllcitiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
